[
  { id: 0, displayName: "Alice", members: null, isTeam: false },
  { id: 1, displayName: "Bob", members: null, isTeam: false },
  { id: 2, displayName: "Carlos", members: null, isTeam: false },
  { id: 3, displayName: "Carol", members: null, isTeam: false },
  { id: 4, displayName: "Charlie", members: null, isTeam: false },
  { id: 5, displayName: "Chuck", members: null, isTeam: false },
  { id: 6, displayName: "Dave", members: null, isTeam: false },
  { id: 7, displayName: "Eve", members: null, isTeam: false },
  { id: 8, displayName: "Mallory", members: null, isTeam: false },
  { id: 9, displayName: "Peggy", members: null, isTeam: false },
  { id: 10, displayName: "Trent", members: null, isTeam: false },
  { id: 11, displayName: "Victor", members: null, isTeam: false },
  { id: 12, displayName: "Walter", members: null, isTeam: false },
  {
    id: 90,
    displayName: "The A-Team",
    members: [
      { id: 0, displayName: "Alice", members: null, isTeam: false },
      { id: 1, displayName: "Bob", members: null, isTeam: false },
      { id: 2, displayName: "Carlos", members: null, isTeam: false },
    ],
    isTeam: true,
  },
  {
    id: 91,
    displayName: "The B-Team",
    members: [
      { id: 9, displayName: "Peggy", members: null, isTeam: false },
      { id: 10, displayName: "Trent", members: null, isTeam: false },
      { id: 11, displayName: "Victor", members: null, isTeam: false },
      { id: 1, displayName: "Bob", members: null, isTeam: false },
    ],
    isTeam: true,
  },
  {
    id: 92,
    displayName: "The C-Team",
    members: [
      { id: 4, displayName: "Charlie", members: null, isTeam: false },
      { id: 7, displayName: "Eve", members: null, isTeam: false },
      { id: 0, displayName: "Alice", members: null, isTeam: false },
      { id: 1, displayName: "Bob", members: null, isTeam: false },
    ],
    isTeam: true,
  },
];
